### PR TITLE
dbt 20 compatibility updates

### PR DESCRIPTION
**Pull request by fivetran-joemarkiewicz**
**Are you a current Fivetran customer?** 

Fivetran created PR

**What change(s) does this PR introduce?** 

This PR introduces dbt 20 compatibility

**Does this PR introduce a breaking change?**

- [X] Yes (please provide breaking change details below.)
- [ ] No  (please provide explanation how the change is non breaking below.)

This PR contains breaking changes in the form of dbt 20 package dependencies

**Is this PR in response to a previously created Issue**

- [ ] Yes, Issue [link issue number here]
- [X] No 

**How did you test the PR changes?** 

 
- [X] CircleCi  
- [ ] Other (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 
- [X] BigQuery
- [X] Redshift
- [X] Snowflake
- [X] Postgres
- [X] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
🆙 

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Review by fivetran-joemarkiewicz — COMMENTED** [review]
As all circle tests have passed I am comfortable merging

**Comment by alanzfu** [comment]
You guys merging this soon? Eagerly waiting :)

**Comment by fivetran-joemarkiewicz** [comment]
> You guys merging this soon? Eagerly waiting :)

Hey @alanzfu we are eagerly awaiting as well 😄 ! We actually recently made this package compatibile with Spark and there is a dbt-spark issue that was recently identified and merged which we are waiting to be released before we merge this PR and cut the new release. 

We are keeping out eyes on the next release of dbt-spark and will let you know once we are able to move forward as we do not want to cut a release of this package with parts that could fail for some users.

**Comment by fivetran-jamie** [comment]
fyi closing this PR and batching dbt 20 changes into https://github.com/fivetran/dbt_jira_source/pull/19 which will be merged shortly 😃

**Pull request closed without merging**
